name: Test Gap Issue Template
description: File a test gap issue.
title: "[Test Gap][{Feature:}][{topo:}][{title}]"
labels: ["Test Gap"]
projects: ["sonic-mgmt"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this test gap issue!

        If you are reporting a new test gap, make sure that we do not have any duplicates already open. You can ensure this by searching the issue list in this repository. If there is a duplicate, please close your issue and add a comment to the existing issue instead.

  - type: markdown
    id: tc-contact-links
    attributes:
      value: |
        Please ask and answer questions here at the [SONiC Support Forums](https://groups.google.com/forum/#!forum/sonicproject)
  - type: textarea
    id: tc-description
    attributes:
      label: Test Gap Description
      description: Why do we need this test gap?
      placeholder: Describe the test gap
    validations:
      required: true
  - type: textarea
    id: tc-results
    attributes:
      label: Results you see
      description: Results you see
      placeholder: Describe the results you saw
    validations:
      required: true
  - type: textarea
    id: tc-expected-results
    attributes:
      label: Results you expected to see
      description: Results you expected to see
      placeholder: Describe the results you expected to see
    validations:
      required: true
  - type: dropdown
    id: tc-platform
    attributes:
      label: Is it platform/topology specific?
      description: Platform or Topology name
      options:
        - generic
        - barefoot
        - broadcom
        - cavium
        - centec
        - innovium
        - marvell
        - mellanox
        - nephos
      default: 0
    validations:
      required: true
  - type: textarea
    id: tc-logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: tc-output
    attributes:
      label: Output of `show version`
      description: Please copy and paste output of `show version`. This will be automatically formatted into code, so no need for backticks
      render: shell
  - type: markdown
    id: tc-attach-logs
    attributes:
      value: |
        Attach files if you need.
  - type: textarea
    id: tc-attachments
    attributes:
      label: Attach files (if any)
